In [1]:
import pandas as pd
import numpy as np
#Encoding modules
import ast
import sys
sys.path.append('../modules')
from encoding_module import json_to_DF
from encoding_module import onehot_json
#Plots
from plot_module import barPlot
from plot_module import featureAnalysis
#API
import requests
import concurrent.futures
#Ignore Warning
import warnings
warnings.filterwarnings("ignore")

In [6]:
movies_metadata = pd.read_csv('../encoding/encoded/movies_metadata_encoded.csv')

In [7]:
movies_metadata

,id,imdb_id,popularity,release_date,runtime,vote_average,vote_count,adult_False,adult_True,Single,...,Latviešu,isiZulu,ਪੰਜਾਬੀ,euskera,Bahasa melayu,Wolof,others_spoken_languages,year,Runtime Category,Vote
0,862,tt0114709,21.946943,1995-10-30,81.0,7.7,5415.0,1,0,0,...,0,0,0,0,0,0,1,1995,2,41695.5
1,8844,tt0113497,17.015539,1995-12-15,104.0,6.9,2413.0,1,0,1,...,0,0,0,0,0,0,1,1995,2,16649.7
2,15602,tt0113228,11.712900,1995-12-22,101.0,6.5,92.0,1,0,0,...,0,0,0,0,0,0,1,1995,2,598.0
3,31357,tt0114885,3.859495,1995-12-22,127.0,6.1,34.0,1,0,1,...,0,0,0,0,0,0,1,1995,2,207.4
4,11862,tt0113041,8.387519,1995-02-10,106.0,5.7,173.0,1,0,0,...,0,0,0,0,0,0,1,1995,2,986.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36378,289923,tt0252966,0.386450,2000-10-03,30.0,7.0,1.0,1,0,1,...,0,0,0,0,0,0,1,2000,1,7.0
36379,222848,tt0112613,0.661558,1995-01-01,85.0,3.5,1.0,1,0,1,...,0,0,0,0,0,0,1,1995,2,3.5
36380,30840,tt0102797,5.683753,1991-05-13,104.0,5.7,26.0,1,0,1,...,0,0,0,0,0,0,1,1991,2,148.2
36381,111109,tt2028550,0.178241,2011-11-17,360.0,9.0,3.0,1,0,1,...,0,0,0,0,0,0,1,2011,4,27.0
36382,67758,tt0303758,0.903007,2003-08-01,90.0,3.8,6.0,1,0,1,...,0,0,0,0,0,0,1,2003,2,22.8

In [11]:
movieID = movies_metadata['id'].tolist()